maskarade/Android-Orma

example/src/main/java/com/github/gfx/android/orma/example/BenchmarkActivity.java
library/src/main/java/com/github/gfx/android/orma/Inserter.java
library/src/main/java/com/github/gfx/android/orma/OrmaConnection.java

As `Updater#execute()` and `Deleter#execute()` are.

rename Inserter#insert() to #execute()

---

README.md

Fix dependencies typo at README.md

---

library/src/test/java/com/github/gfx/android/orma/test/AccessorsTest.java
library/src/test/java/com/github/gfx/android/orma/test/model/ModelWithAccessors.java
processor/src/main/java/com/github/gfx/android/orma/processor/ColumnDefinition.java
processor/src/main/java/com/github/gfx/android/orma/processor/SchemaDefinition.java
processor/src/main/java/com/github/gfx/android/orma/processor/SchemaValidator.java
processor/src/main/java/com/github/gfx/android/orma/processor/SchemaWriter.java

Support simple accessors

---

library/src/main/java/com/github/gfx/android/orma/ColumnDef.java
library/src/main/java/com/github/gfx/android/orma/Deleter.java
library/src/main/java/com/github/gfx/android/orma/Inserter.java
library/src/main/java/com/github/gfx/android/orma/OrmaConnection.java
library/src/main/java/com/github/gfx/android/orma/Relation.java
library/src/main/java/com/github/gfx/android/orma/Schema.java
library/src/main/java/com/github/gfx/android/orma/Updater.java
library/src/main/java/com/github/gfx/android/orma/adapter/AbstractTypeAdapter.java
library/src/main/java/com/github/gfx/android/orma/adapter/StringListAdapter.java
library/src/main/java/com/github/gfx/android/orma/adapter/StringSetAdapter.java
library/src/main/java/com/github/gfx/android/orma/adapter/TypeAdapter.java
library/src/main/java/com/github/gfx/android/orma/adapter/TypeAdapterRegistry.java
library/src/main/java/com/github/gfx/android/orma/adapter/UriAdapter.java
library/src/main/java/com/github/gfx/android/orma/exception/TypeAdapterNotFoundException.java
library/src/main/java/com/github/gfx/android/orma/internal/OrmaConditionBase.java
library/src/main/java/com/github/gfx/android/orma/internal/ParameterizedTypes.java
library/src/test/java/com/github/gfx/android/orma/test/ModelSpecTest.java
library/src/test/java/com/github/gfx/android/orma/test/TypeAdaptersTest.java
library/src/test/java/com/github/gfx/android/orma/test/model/ModelWithTypeAdapters.java
processor/src/main/java/com/github/gfx/android/orma/processor/DatabaseWriter.java
processor/src/main/java/com/github/gfx/android/orma/processor/SchemaWriter.java
processor/src/main/java/com/github/gfx/android/orma/processor/Types.java
processor/src/main/java/com/github/gfx/android/orma/processor/UpdaterWriter.java

implement type adapters

---

example/src/main/java/com/github/gfx/android/orma/example/activity/BenchmarkActivity.java

`realm.allObjects() -> RealmResults<T>` does not execute any query unless one fetches models from the `RealmResults<T>`.
I have fixed this issue and run BenchmarkActivity; a result shows Orma is as fast as Realm:
Seems really great.

fix benchmark; Realm executed no query!

---

library/src/main/java/com/github/gfx/android/orma/Schema.java
processor/src/main/java/com/github/gfx/android/orma/processor/SchemaWriter.java

remove populateValuesIntoModel(), which was redundant

---

README.md

Fix Twitter account link typo at README.md

Fix Twitter account link typo at README

---

library/src/main/java/com/github/gfx/android/orma/internal/OrmaConditionBase.java
library/src/test/java/com/github/gfx/android/orma/test/AccessorsTest.java
library/src/test/java/com/github/gfx/android/orma/test/ConditionHelpersTest.java
library/src/test/java/com/github/gfx/android/orma/test/model/ModelWithConditionHelpers.java
processor/src/main/java/com/github/gfx/android/orma/processor/ColumnDefinition.java
processor/src/main/java/com/github/gfx/android/orma/processor/ConditionHelpers.java
processor/src/main/java/com/github/gfx/android/orma/processor/DeleterWriter.java
processor/src/main/java/com/github/gfx/android/orma/processor/RelationWriter.java
processor/src/main/java/com/github/gfx/android/orma/processor/SqlGenerator.java
processor/src/main/java/com/github/gfx/android/orma/processor/Types.java
processor/src/main/java/com/github/gfx/android/orma/processor/UpdaterWriter.java

Condition Helpers

---

build.gradle
library/src/main/java/com/github/gfx/android/orma/OrmaConfiguration.java
library/src/main/java/com/github/gfx/android/orma/OrmaConnection.java
library/src/main/java/com/github/gfx/android/orma/Schema.java
library/src/main/java/com/github/gfx/android/orma/SingleRelation.java
library/src/test/java/com/github/gfx/android/orma/test/ModelSpecTest.java
library/src/test/java/com/github/gfx/android/orma/test/QueryTest.java
library/src/test/java/com/github/gfx/android/orma/test/ReservedWordsTest.java
library/src/test/java/com/github/gfx/android/orma/test/RxObservableTest.java
library/src/test/java/com/github/gfx/android/orma/test/model/Where.java
metadata.gradle
migration/src/main/java/com/github/gfx/android/orma/migration/SchemaDiffMigration.java
migration/src/test/java/com/github/gfx/android/orma/migration/test/ManualStepMigrationTest.java
migration/src/test/java/com/github/gfx/android/orma/migration/test/SchemaDiffTest.java
processor/src/main/java/com/github/gfx/android/orma/processor/ConditionQueryHelpers.java
processor/src/main/java/com/github/gfx/android/orma/processor/DeleterWriter.java
processor/src/main/java/com/github/gfx/android/orma/processor/RelationWriter.java
processor/src/main/java/com/github/gfx/android/orma/processor/SchemaWriter.java
processor/src/main/java/com/github/gfx/android/orma/processor/UpdaterWriter.java
settings.gradle

* Allows reserved words in models
* Apply "Reformat Code"

Allows reserved words in table names and column names

---

example/src/main/java/com/github/gfx/android/orma/example/activity/TodoActivity.java
example/src/main/java/com/github/gfx/android/orma/example/orma/Todo.java
library/src/main/java/com/github/gfx/android/orma/Inserter.java
library/src/main/java/com/github/gfx/android/orma/OrmaConnection.java
library/src/main/java/com/github/gfx/android/orma/Relation.java
library/src/main/java/com/github/gfx/android/orma/SingleRelation.java
library/src/test/java/com/github/gfx/android/orma/test/QueryTest.java
processor/src/main/java/com/github/gfx/android/orma/processor/ConditionQueryHelpers.java
processor/src/main/java/com/github/gfx/android/orma/processor/RelationWriter.java
processor/src/main/java/com/github/gfx/android/orma/processor/Strings.java

Support `orma.selectFrom*().get(position)` for ListAdapter.

support partial reading

---

example/src/main/java/com/github/gfx/android/orma/example/activity/BenchmarkActivity.java
example/src/main/java/com/github/gfx/android/orma/example/handwritten/HandWrittenOpenHelper.java
example/src/main/java/com/github/gfx/android/orma/example/realm/RealmTodo.java

In reality, fetching with no order makes no sense.

sort in BenchmarkActivity

---

library/src/test/java/com/github/gfx/android/orma/test/QueryTest.java
processor/src/main/java/com/github/gfx/android/orma/processor/BaseWriter.java
processor/src/main/java/com/github/gfx/android/orma/processor/ColumnDefinition.java
processor/src/main/java/com/github/gfx/android/orma/processor/DatabaseWriter.java
processor/src/main/java/com/github/gfx/android/orma/processor/DeleterWriter.java
processor/src/main/java/com/github/gfx/android/orma/processor/OrmaProcessor.java
processor/src/main/java/com/github/gfx/android/orma/processor/ProcessingContext.java
processor/src/main/java/com/github/gfx/android/orma/processor/RelationDefinition.java
processor/src/main/java/com/github/gfx/android/orma/processor/RelationWriter.java
processor/src/main/java/com/github/gfx/android/orma/processor/SchemaWriter.java
processor/src/main/java/com/github/gfx/android/orma/processor/UpdaterWriter.java
processor/src/test/java/com/github/gfx/android/orma/processor/test/SchemaValidatorTest.java

SingleRelation for Updater

---

processor/src/main/java/com/github/gfx/android/orma/processor/OrmaProcessor.java
processor/src/main/java/com/github/gfx/android/orma/processor/ProcessingContext.java
processor/src/main/java/com/github/gfx/android/orma/processor/ProcessingException.java
processor/src/main/java/com/github/gfx/android/orma/processor/SchemaValidator.java

stack processing errros and print them in the end of processing

---

annotations/src/main/java/com/github/gfx/android/orma/annotation/Table.java
library/src/test/java/com/github/gfx/android/orma/test/ModelSpecTest.java
library/src/test/java/com/github/gfx/android/orma/test/model/ModelWithConstraints.java
migration/src/main/java/com/github/gfx/android/orma/migration/SchemaDiffMigration.java
migration/src/test/java/com/github/gfx/android/orma/migration/test/TableDiffTest.java
processor/src/main/java/com/github/gfx/android/orma/processor/SchemaDefinition.java
processor/src/main/java/com/github/gfx/android/orma/processor/SqlGenerator.java

implement table constraints

---

library/src/test/java/com/github/gfx/android/orma/test/QueryTest.java
processor/src/main/java/com/github/gfx/android/orma/processor/RelationWriter.java

order-by helers should be generated to any type of columns

---

library/src/main/java/com/github/gfx/android/orma/Relation.java
library/src/test/java/com/github/gfx/android/orma/test/OrmaDatabaseTest.java
library/src/test/java/com/github/gfx/android/orma/test/QueryTest.java

Will be useful for combination of `groupBy()` and `having()`. ref. #39 
```java
Cursor cursor = db.selectFromBook()
.executeWithColumns("max(id) as max_id, min(id) as min_id");
```

Relation#execute() and #executeWithColumns()

---

library/src/main/java/com/github/gfx/android/orma/OrmaConnection.java
library/src/main/java/com/github/gfx/android/orma/Schema.java
library/src/test/java/com/github/gfx/android/orma/test/QueryTest.java
library/src/test/java/com/github/gfx/android/orma/test/model/Author.java
processor/src/main/java/com/github/gfx/android/orma/processor/DatabaseWriter.java
processor/src/main/java/com/github/gfx/android/orma/processor/SchemaWriter.java
processor/src/main/java/com/github/gfx/android/orma/processor/SqlGenerator.java

prepareInsertOrReplaceInto*() for upsert operation

---

README.md
annotations/src/main/java/com/github/gfx/android/orma/annotation/Setter.java
library/src/test/java/com/github/gfx/android/orma/test/SetterAndGetterTest.java
library/src/test/java/com/github/gfx/android/orma/test/model/ModelWithConstructorSetter.java
library/src/test/java/com/github/gfx/android/orma/test/model/ModelWithNamedSetterConstructor.java
library/src/test/java/com/github/gfx/android/orma/test/model/ModelWithSetterConstructor.java
processor/src/main/java/com/github/gfx/android/orma/processor/ColumnDefinition.java
processor/src/main/java/com/github/gfx/android/orma/processor/SchemaDefinition.java
processor/src/main/java/com/github/gfx/android/orma/processor/SchemaWriter.java
processor/src/main/java/com/github/gfx/android/orma/processor/UpdaterWriter.java

resolve #21 
See `ModelWithConstructorSetter.java` and `ModelWithNamedSetterConstructor.java` for how-to-use.

support immutable models by adding @Setter to constructors

---

library/src/main/java/com/github/gfx/android/orma/Deleter.java
library/src/main/java/com/github/gfx/android/orma/Relation.java
library/src/main/java/com/github/gfx/android/orma/Updater.java
library/src/main/java/com/github/gfx/android/orma/internal/OrmaConditionBase.java
library/src/test/java/com/github/gfx/android/orma/test/QueryTest.java
processor/src/main/java/com/github/gfx/android/orma/processor/DeleterWriter.java
processor/src/main/java/com/github/gfx/android/orma/processor/RelationWriter.java
processor/src/main/java/com/github/gfx/android/orma/processor/UpdaterWriter.java

feature to create Deleter and Updater from Relation 

---

Dockerfile
circle.yml

cf.
* https://discuss.circleci.com/t/unable-to-use-docker-cp-but-it-worked-2-days-ago/1137/7

Tweaks for CircleCI

---

library/src/main/java/com/github/gfx/android/orma/OrmaConnection.java
library/src/main/java/com/github/gfx/android/orma/adapter/AbstractTypeAdapter.java
library/src/main/java/com/github/gfx/android/orma/adapter/TypeAdapter.java
library/src/main/java/com/github/gfx/android/orma/adapter/TypeAdapterRegistry.java
library/src/main/java/com/github/gfx/android/orma/internal/OrmaConditionBase.java
library/src/test/java/com/github/gfx/android/orma/test/ConditionHelpersTest.java
library/src/test/java/com/github/gfx/android/orma/test/ModelSpecTest.java
library/src/test/java/com/github/gfx/android/orma/test/TypeAdaptersTest.java
library/src/test/java/com/github/gfx/android/orma/test/model/ModelWithConditionHelpers.java
library/src/test/java/com/github/gfx/android/orma/test/model/ModelWithTypeAdapters.java
processor/src/main/java/com/github/gfx/android/orma/processor/ColumnDefinition.java
processor/src/main/java/com/github/gfx/android/orma/processor/ConditionQueryHelpers.java
processor/src/main/java/com/github/gfx/android/orma/processor/SchemaDefinition.java
processor/src/main/java/com/github/gfx/android/orma/processor/SchemaWriter.java
processor/src/main/java/com/github/gfx/android/orma/processor/UpdaterWriter.java

Apply TypeAdapter to condition helpers

---

library/src/main/java/com/github/gfx/android/orma/OrmaConnection.java
library/src/main/java/com/github/gfx/android/orma/Relation.java
library/src/main/java/com/github/gfx/android/orma/Schema.java
processor/src/main/java/com/github/gfx/android/orma/processor/DatabaseWriter.java
processor/src/main/java/com/github/gfx/android/orma/processor/SchemaWriter.java

add OrmaDatabase#load*fromCursor and s/create*/new*/

---

library/src/test/java/com/github/gfx/android/orma/test/model/ModelWithAccessors.java
processor/src/main/java/com/github/gfx/android/orma/processor/OrmaProcessor.java
processor/src/main/java/com/github/gfx/android/orma/processor/ProcessingContext.java
processor/src/main/java/com/github/gfx/android/orma/processor/SchemaDefinition.java
processor/src/main/java/com/github/gfx/android/orma/processor/SchemaWriter.java

support "is" prefix for getters

---

example/src/main/java/com/github/gfx/android/orma/example/handwritten/HandWrittenOpenHelper.java
library/src/main/java/com/github/gfx/android/orma/adapter/AbstractTypeAdapter.java
library/src/main/java/com/github/gfx/android/orma/adapter/TypeAdapterRegistry.java
library/src/main/java/com/github/gfx/android/orma/internal/EquatableTypeWrapper.java
library/src/main/java/com/github/gfx/android/orma/internal/TypeHolder.java
library/src/test/java/com/github/gfx/android/orma/test/TypeAdaptersTest.java
processor/src/main/java/com/github/gfx/android/orma/processor/SchemaWriter.java
processor/src/main/java/com/github/gfx/android/orma/processor/Types.java

ParameterizedType impl is broken on older Android

---

library/build.gradle
library/src/androidTest/java/com
library/src/test/java/android/support/test/InstrumentationRegistry.java
library/src/test/java/android/support/test/runner/AndroidJUnit4.java
library/src/test/java/com/github/gfx/android/orma/test/ConditionHelpersTest.java
library/src/test/java/com/github/gfx/android/orma/test/ForeignKeysTest.java
library/src/test/java/com/github/gfx/android/orma/test/MigrationEngineTest.java
library/src/test/java/com/github/gfx/android/orma/test/ModelSpecTest.java
library/src/test/java/com/github/gfx/android/orma/test/OrmaDatabaseTest.java
library/src/test/java/com/github/gfx/android/orma/test/QueryTest.java
library/src/test/java/com/github/gfx/android/orma/test/ReservedWordsTest.java
library/src/test/java/com/github/gfx/android/orma/test/RxObservableTest.java
library/src/test/java/com/github/gfx/android/orma/test/SchemaTest.java
library/src/test/java/com/github/gfx/android/orma/test/SetterAndGetterTest.java
library/src/test/java/com/github/gfx/android/orma/test/TypeAdaptersTest.java
library/src/test/resources/robolectric.properties
processor/src/main/java/com/github/gfx/android/orma/processor/SchemaWriter.java

Now `./gradlew connectedAndroidTest` works!

Hack to run Robolectric tests as Android Instrumentation Tests

---

example/src/main/java/com/github/gfx/android/orma/example/activity/TodoActivity.java
library/build.gradle
library/src/main/java/com/github/gfx/android/orma/OrmaConnection.java
library/src/main/java/com/github/gfx/android/orma/Relation.java
library/src/main/java/com/github/gfx/android/orma/internal/OrmaConditionBase.java
library/src/main/java/com/github/gfx/android/orma/widget/OrmaAdapterDelegate.java
library/src/main/java/com/github/gfx/android/orma/widget/OrmaListAdapter.java
library/src/main/java/com/github/gfx/android/orma/widget/OrmaRecyclerViewAdapter.java
library/src/test/java/com/github/gfx/android/orma/test/OrmaAdapterDelegateTest.java

implement OrmaRecyclerViewAdapter

---

library/src/main/java/com/github/gfx/android/orma/ColumnDef.java
library/src/main/java/com/github/gfx/android/orma/Relation.java
library/src/main/java/com/github/gfx/android/orma/Selector.java
library/src/main/java/com/github/gfx/android/orma/SingleAssociation.java
library/src/main/java/com/github/gfx/android/orma/internal/OrmaConditionBase.java
library/src/test/java/com/github/gfx/android/orma/test/RelationTest.java
library/src/test/java/com/github/gfx/android/orma/test/model/Author.java
library/src/test/java/com/github/gfx/android/orma/test/model/ModelWithMultipleSortableColumns.java
migration/src/test/java/com/github/gfx/android/orma/migration/test/TestUtils.java
migration/src/test/java/com/github/gfx/android/orma/migration/test/sqliteparser/SQLiteParserUtilsTest.java

Relation#truncateWithTransactionAsObservable()

---

migration/src/main/java/com/github/gfx/android/orma/migration/ManualStepMigration.java
migration/src/test/java/com/github/gfx/android/orma/migration/test/ManualStepMigrationTest.java

* orma_migration_steps might be broken because it depends on System.currentTimeMillis()
* **orma_migration_steps is not compatible before v0.23.0**

fix a CRITICAL bug in ManualStepMigration

---

library/src/main/java/com/github/gfx/android/orma/Relation.java
processor/src/main/java/com/github/gfx/android/orma/processor/RelationWriter.java

remove selector delegates in Relation

---

annotations/src/main/java/com/github/gfx/android/orma/annotation/Column.java
library/src/test/java/com/github/gfx/android/orma/test/SchemaTest.java
library/src/test/java/com/github/gfx/android/orma/test/model/ModelWithStorageTypes.java
processor/src/main/java/com/github/gfx/android/orma/processor/ColumnDefinition.java
processor/src/main/java/com/github/gfx/android/orma/processor/SchemaWriter.java
processor/src/main/java/com/github/gfx/android/orma/processor/SqlGenerator.java

This is useful for migration from other ORMs.

add Column#storageType option

---

library/src/main/java/com/github/gfx/android/orma/OrmaConnection.java
library/src/test/java/com/github/gfx/android/orma/test/OrmaDatabaseTest.java

fix resetDatabase()

---

example/src/main/java/com/github/gfx/android/orma/example/activity/MainActivity.java
library/src/main/java/com/github/gfx/android/orma/Relation.java
library/src/main/java/com/github/gfx/android/orma/Selector.java

Combination queries, or read-write operations, should be defined in Relation.
Amend #126.

move getOrCreate() to Relation

---

library/src/main/java/com/github/gfx/android/orma/OrmaConnection.java
migration/src/main/java/com/github/gfx/android/orma/migration/ManualStepMigration.java

Migration Logginng

---

example/src/main/java/com/github/gfx/android/orma/example/activity/BenchmarkActivity.java
example/src/main/java/com/github/gfx/android/orma/example/activity/ListViewActivity.java
example/src/main/java/com/github/gfx/android/orma/example/activity/MainActivity.java
example/src/main/java/com/github/gfx/android/orma/example/activity/RecyclerViewActivity.java
example/src/main/java/com/github/gfx/android/orma/example/handwritten/HandWrittenOpenHelper.java
example/src/main/java/com/github/gfx/android/orma/example/orma/Todo.java
example/src/main/java/com/github/gfx/android/orma/example/realm/RealmTodo.java

Note that #131 will get better performance for type adapters.

use type adapters in the example app

---

CHANGELOG.md
README.md
library/src/test/java/com/github/gfx/android/orma/test/model/ModelWithNamedSetterConstructor.java
processor/src/main/java/com/github/gfx/android/orma/processor/SchemaDefinition.java
processor/src/main/java/com/github/gfx/android/orma/processor/SchemaWriter.java
version.properties

Fix constructor param names

---

build.gradle
processor/build.gradle
processor/src/test/java/com/github/gfx/android/orma/processor/test/SchemaValidatorTest.java
processor/src/test/resources/CaseInsensitiveDuplication.java
processor/src/test/resources/ColumnNameDuplication.java
processor/src/test/resources/NoColumn.java
processor/src/test/resources/PrimaryKeyAndColumnNamesDuplication.java

Use `JavaFileObjects.forResource()`

refactor processor tests

---

processor/src/main/java/com/github/gfx/android/orma/processor/SchemaDefinition.java
processor/src/main/java/com/github/gfx/android/orma/processor/SchemaValidator.java
processor/src/main/java/com/github/gfx/android/orma/processor/SchemaWriter.java
processor/src/test/java/com/github/gfx/android/orma/processor/test/SchemaValidatorTest.java
processor/src/test/resources/TooManySetterConstructors.java

close #68 
* prohibit `@Setter` for default constructors. i.e. `@Setter T()` is now invalid
* prohibit multiple `@Setter` constructors

Strict check for @Setter constructor

---

library/src/test/java/com/github/gfx/android/orma/test/SetterAndGetterTest.java
library/src/test/java/com/github/gfx/android/orma/test/model/ModelWithSetterConstructorAndNullable.java
processor/src/main/java/com/github/gfx/android/orma/processor/SchemaWriter.java

@Nullable and @Setter constructors generate wrong code

---

README.md
library/src/main/java/com/github/gfx/android/orma/SingleAssociation.java
library/src/main/java/com/github/gfx/android/orma/gson/SingleAssociationTypeAdapterFactory.java
library/src/main/java/com/github/gfx/android/orma/internal/Schemas.java
library/src/test/java/com/github/gfx/android/orma/test/GsonTypeAdapterTest.java
processor/src/main/java/com/github/gfx/android/orma/processor/SchemaWriter.java
processor/src/main/java/com/github/gfx/android/orma/processor/Types.java

See http://google.github.io/gson/apidocs/com/google/gson/annotations/JsonAdapter.html for details.

Use Gson @JsonAdapter to register gson type adapters automatically

---

example/src/main/java/com/github/gfx/android/orma/example/activity/MainActivity.java
example/src/main/java/com/github/gfx/android/orma/example/orma/Category.java
library/src/main/java/com/github/gfx/android/orma/ColumnDef.java
library/src/main/java/com/github/gfx/android/orma/SingleAssociation.java
library/src/main/java/com/github/gfx/android/orma/exception/InvalidModelException.java
library/src/test/java/com/github/gfx/android/orma/test/ParcelableTest.java
library/src/test/java/com/github/gfx/android/orma/test/model/Author.java
library/src/test/java/com/github/gfx/android/orma/test/model/ModelParcelable.java

make SingleAssociation parcelable

---

example/src/main/java/com/github/gfx/android/orma/example/activity/MainActivity.java
library/src/main/java/com/github/gfx/android/orma/OrmaConfiguration.java
library/src/main/java/com/github/gfx/android/orma/OrmaConnection.java
library/src/main/java/com/github/gfx/android/orma/exception/InvalidModelException.java
library/src/test/java/com/github/gfx/android/orma/test/MigrationEngineTest.java
library/src/test/java/com/github/gfx/android/orma/test/OrmaDatabaseTest.java
migration/README.md
migration/src/main/java/com/github/gfx/android/orma/migration/AbstractMigrationEngine.java
migration/src/main/java/com/github/gfx/android/orma/migration/ManualStepMigration.java
migration/src/main/java/com/github/gfx/android/orma/migration/MigrationEngine.java
migration/src/main/java/com/github/gfx/android/orma/migration/OrmaMigration.java
migration/src/main/java/com/github/gfx/android/orma/migration/SchemaDiffMigration.java
migration/src/test/java/com/github/gfx/android/orma/migration/test/IndexDiffTest.java
migration/src/test/java/com/github/gfx/android/orma/migration/test/ManualStepMigrationTest.java
migration/src/test/java/com/github/gfx/android/orma/migration/test/OrmaMigrationTest.java
migration/src/test/java/com/github/gfx/android/orma/migration/test/SchemaDiffMigrationTest.java
migration/src/test/java/com/github/gfx/android/orma/migration/test/TableDiffTest.java
processor/src/main/java/com/github/gfx/android/orma/processor/DatabaseWriter.java
processor/src/main/java/com/github/gfx/android/orma/processor/SchemaDefinition.java
processor/src/main/java/com/github/gfx/android/orma/processor/SchemaWriter.java
processor/src/main/java/com/github/gfx/android/orma/processor/SqlGenerator.java

Hash based migration triggers

---

library/src/main/java/com/github/gfx/android/orma/OrmaConfiguration.java
library/src/test/java/com/github/gfx/android/orma/test/MigrationEngineTest.java

Add `OrmaDatabase.Builder#migrationStep()` to define migration steps with OrmaMigration (ManualStepMigration).

integrate MigrationEngine to OrmaDatabase.Builder

---

example/src/main/java/com/github/gfx/android/orma/example/activity/MainActivity.java
library/src/test/java/com/github/gfx/android/orma/test/MigrationEngineTest.java
processor/src/main/java/com/github/gfx/android/orma/processor/DatabaseWriter.java
processor/src/main/java/com/github/gfx/android/orma/processor/Types.java

`OrmaDatabase#migrate() throws SQLiteConstraintException`

add OrmaDatabase#migrate() to explicitly invoke database migration

---

example/src/main/java/com/github/gfx/android/orma/example/orma/Category.java
example/src/main/java/com/github/gfx/android/orma/example/orma/Item.java
example/src/main/java/com/github/gfx/android/orma/example/orma/Todo.java
library/src/main/java/com/github/gfx/android/orma/ColumnDef.java
library/src/main/java/com/github/gfx/android/orma/Inserter.java
library/src/main/java/com/github/gfx/android/orma/OrmaConnection.java
library/src/main/java/com/github/gfx/android/orma/Relation.java
library/src/main/java/com/github/gfx/android/orma/Schema.java
library/src/main/java/com/github/gfx/android/orma/Selector.java
library/src/main/java/com/github/gfx/android/orma/SingleAssociation.java
library/src/test/java/com/github/gfx/android/orma/test/DirectAssociationsTest.java
library/src/test/java/com/github/gfx/android/orma/test/ForeignKeysTest.java
library/src/test/java/com/github/gfx/android/orma/test/model/ModelWithDirectAssociation.java
processor/src/main/java/com/github/gfx/android/orma/processor/Annotations.java
processor/src/main/java/com/github/gfx/android/orma/processor/AssociationDefinition.java
processor/src/main/java/com/github/gfx/android/orma/processor/ColumnDefinition.java
processor/src/main/java/com/github/gfx/android/orma/processor/ConditionQueryHelpers.java
processor/src/main/java/com/github/gfx/android/orma/processor/DatabaseWriter.java
processor/src/main/java/com/github/gfx/android/orma/processor/RelationWriter.java
processor/src/main/java/com/github/gfx/android/orma/processor/SchemaDefinition.java
processor/src/main/java/com/github/gfx/android/orma/processor/SchemaWriter.java
processor/src/main/java/com/github/gfx/android/orma/processor/SqlGenerator.java
processor/src/main/java/com/github/gfx/android/orma/processor/SqlTypes.java
processor/src/main/java/com/github/gfx/android/orma/processor/Types.java
processor/src/main/java/com/github/gfx/android/orma/processor/UpdaterWriter.java

Resolve #24 
* Data structure is compatible with indirect associations (or `SingleAssociation`)
* No lazy loading
* Foreign-key constraints are applied implicitly
* Explicit queries (#25) are not yet supported
See `Item.java` and `Category.java`.

Direct Associations

---

library/src/test/java/com/github/gfx/android/orma/test/SchemaTest.java
processor/src/main/java/com/github/gfx/android/orma/processor/DatabaseWriter.java
processor/src/main/java/com/github/gfx/android/orma/processor/ProcessingContext.java
processor/src/main/java/com/github/gfx/android/orma/processor/SchemaDefinition.java
processor/src/main/java/com/github/gfx/android/orma/processor/SchemaWriter.java

This change reduces runtime memory.

remove OrmaDatabase.schemaFoo. Use Foo_Schema.INSTANCE instead.

---

processor/src/main/java/com/github/gfx/android/orma/processor/ColumnDefinition.java
processor/src/main/java/com/github/gfx/android/orma/processor/SchemaDefinition.java
processor/src/main/java/com/github/gfx/android/orma/processor/SchemaWriter.java

fix NPE on direct associations without primary keys

---

example/build/generated/source/apt/debug/com/github/gfx/android/orma/example/orma/Item_Deleter.java
example/build/generated/source/apt/debug/com/github/gfx/android/orma/example/orma/Item_Relation.java
example/build/generated/source/apt/debug/com/github/gfx/android/orma/example/orma/Item_Selector.java
example/build/generated/source/apt/debug/com/github/gfx/android/orma/example/orma/Item_Updater.java
library/src/test/java/com/github/gfx/android/orma/test/DirectAssociationsTest.java
processor/src/main/java/com/github/gfx/android/orma/processor/ConditionQueryHelpers.java

add helpers to find models by associated model keys

---

example/build/generated/source/apt/debug/com/github/gfx/android/orma/example/orma/Item_Deleter.java
example/build/generated/source/apt/debug/com/github/gfx/android/orma/example/orma/Item_Relation.java
example/build/generated/source/apt/debug/com/github/gfx/android/orma/example/orma/Item_Selector.java
example/build/generated/source/apt/debug/com/github/gfx/android/orma/example/orma/Item_Updater.java
library/src/test/java/com/github/gfx/android/orma/test/DirectAssociationsTest.java
library/src/test/java/com/github/gfx/android/orma/test/model/Author.java
library/src/test/java/com/github/gfx/android/orma/test/model/ModelWithDirectAssociation.java
processor/src/main/java/com/github/gfx/android/orma/processor/ColumnDefinition.java
processor/src/main/java/com/github/gfx/android/orma/processor/ConditionQueryHelpers.java
processor/src/main/java/com/github/gfx/android/orma/processor/SchemaDefinition.java
processor/src/main/java/com/github/gfx/android/orma/processor/SelectorWriter.java

but it's not perfect. see #189

use FQN in query helpers if needed

---

migration/src/main/java/com/github/gfx/android/orma/migration/AbstractMigrationEngine.java
migration/src/test/java/com/github/gfx/android/orma/migration/test/AbstractMigrationEngineTest.java

Fix https://github.com/konifar/droidkaigi2016/issues/318 :cry:

fix crashes on migration

---

example/build/generated/source/apt/debug/com/github/gfx/android/orma/example/orma/Category_Deleter.java
example/build/generated/source/apt/debug/com/github/gfx/android/orma/example/orma/Category_Relation.java
example/build/generated/source/apt/debug/com/github/gfx/android/orma/example/orma/Category_Schema.java
example/build/generated/source/apt/debug/com/github/gfx/android/orma/example/orma/Category_Selector.java
example/build/generated/source/apt/debug/com/github/gfx/android/orma/example/orma/Category_Updater.java
example/build/generated/source/apt/debug/com/github/gfx/android/orma/example/orma/Item_Deleter.java
example/build/generated/source/apt/debug/com/github/gfx/android/orma/example/orma/Item_Relation.java
example/build/generated/source/apt/debug/com/github/gfx/android/orma/example/orma/Item_Schema.java
example/build/generated/source/apt/debug/com/github/gfx/android/orma/example/orma/Item_Selector.java
example/build/generated/source/apt/debug/com/github/gfx/android/orma/example/orma/Item_Updater.java
example/build/generated/source/apt/debug/com/github/gfx/android/orma/example/orma/OrmaDatabase.java
example/build/generated/source/apt/debug/com/github/gfx/android/orma/example/orma/Todo_Deleter.java
example/build/generated/source/apt/debug/com/github/gfx/android/orma/example/orma/Todo_Relation.java
example/build/generated/source/apt/debug/com/github/gfx/android/orma/example/orma/Todo_Schema.java
example/build/generated/source/apt/debug/com/github/gfx/android/orma/example/orma/Todo_Selector.java
example/build/generated/source/apt/debug/com/github/gfx/android/orma/example/orma/Todo_Updater.java
library/src/main/java/com/github/gfx/android/orma/OrmaConnection.java
library/src/test/java/com/github/gfx/android/orma/test/SchemaTest.java
migration/src/main/java/com/github/gfx/android/orma/migration/SchemaDiffMigration.java
migration/src/main/java/com/github/gfx/android/orma/migration/SqliteDdlBuilder.java
migration/src/main/java/com/github/gfx/android/orma/migration/sqliteparser/SQLiteComponent.java
migration/src/test/java/com/github/gfx/android/orma/migration/test/IndexDiffTest.java
migration/src/test/java/com/github/gfx/android/orma/migration/test/SchemaDiffMigrationTest.java
migration/src/test/java/com/github/gfx/android/orma/migration/test/TableDiffTest.java
migration/src/test/java/com/github/gfx/android/orma/migration/test/sqliteparser_test/SQLiteComponentTest.java
processor/src/main/java/com/github/gfx/android/orma/processor/generator/SqlGenerator.java

use backquote (`...`) to escape identifiers

---

library/src/test/java/com/github/gfx/android/orma/test/DirectAssociationsTest.java
library/src/test/java/com/github/gfx/android/orma/test/model/ModelWithNestedDirectAssociations.java
processor/src/main/java/com/github/gfx/android/orma/processor/generator/SchemaWriter.java
processor/src/main/java/com/github/gfx/android/orma/processor/model/SchemaDefinition.java

Now it works.
See `ModelWithNestedDirectAssociations.java`.

fix issues where nested direct associations do not work

---

example/build/generated/source/apt/debug/com/github/gfx/android/orma/example/orma/Category_Schema.java
example/build/generated/source/apt/debug/com/github/gfx/android/orma/example/orma/Item_Schema.java
example/build/generated/source/apt/debug/com/github/gfx/android/orma/example/orma/Todo_Schema.java
library/src/main/java/com/github/gfx/android/orma/ColumnDef.java
library/src/main/java/com/github/gfx/android/orma/OrmaConnection.java
library/src/main/java/com/github/gfx/android/orma/Relation.java
library/src/main/java/com/github/gfx/android/orma/SingleAssociation.java
library/src/test/java/com/github/gfx/android/orma/test/RelationTest.java
library/src/test/java/com/github/gfx/android/orma/test/model/ModelWithDate.java
processor/src/main/java/com/github/gfx/android/orma/processor/generator/SchemaWriter.java
processor/src/main/java/com/github/gfx/android/orma/processor/model/ColumnDefinition.java

Added `ColumnDef#getSerialized()`.

close #198; Relation can't sort fields with static type serializers

---

README.md
migration/README.md

update document on migration

---

example/src/main/java/com/github/gfx/android/orma/example/activity/MainActivity.java
example/src/main/res/layout/content_main.xml
migration/src/main/java/com/github/gfx/android/orma/migration/ManualStepMigration.java
migration/src/main/java/com/github/gfx/android/orma/migration/SQLiteMaster.java
migration/src/main/java/com/github/gfx/android/orma/migration/SchemaDiffMigration.java
migration/src/main/java/com/github/gfx/android/orma/migration/SqliteDdlBuilder.java
migration/src/main/java/com/github/gfx/android/orma/migration/sqliteparser/CreateTableStatement.java
migration/src/test/java/com/github/gfx/android/orma/migration/test/UtilityTest.java

See MainActivity.java for how-to-use.

add ManualStepMigration.Helper#renameColumn()

---

library/src/main/java/com/github/gfx/android/orma/Selector.java
library/src/test/java/com/github/gfx/android/orma/test/RxObservableTest.java

Handle unsubscribe events in Observable.create()

---

example/build.gradle
example/proguard-rules.pro
library/proguard-rules.pro

ProGuard settings

---

library/src/main/java/com/github/gfx/android/orma/OrmaConnection.java
library/src/main/java/com/github/gfx/android/orma/Relation.java
library/src/main/java/com/github/gfx/android/orma/Selector.java

add Selector#buildQuery() and its variants

---

migration/src/main/java/com/github/gfx/android/orma/migration/SQLiteMaster.java
migration/src/main/java/com/github/gfx/android/orma/migration/SchemaDiffMigration.java
migration/src/main/java/com/github/gfx/android/orma/migration/SqliteDdlBuilder.java
migration/src/main/java/com/github/gfx/android/orma/migration/sqliteparser/CreateTableStatement.java
migration/src/test/java/com/github/gfx/android/orma/migration/test/SchemaDiffMigrationTest.java

SchemaDiffMigratin uses `PRAGMA schema_version` to invoke migration.

Schema diff migration steps 2

---

processor/src/main/java/com/github/gfx/android/orma/processor/model/SchemaDefinition.java

I don't reproduce #216, but there is an issue in SchemaDefinition.java.

lazy check for a modle has direct associations

---

library/src/test/java/com/github/gfx/android/orma/test/model/ModelWithInvalidJavaIdentifier.java
library/src/test/java/com/github/gfx/android/orma/test/model/ModelWithNamedColumnAndConstructor.java
processor/src/main/java/com/github/gfx/android/orma/processor/model/SchemaDefinition.java

the name resolver might not find getters

---

library/src/main/java/com/github/gfx/android/orma/widget/OrmaAdapter.java

#227 
Almost same as #228 and removes `doOnSuccess()`

fix #227 OrmaAdapter#count() returns a wrong value with conditions

---

library/src/main/java/com/github/gfx/android/orma/Selector.java
library/src/test/java/com/github/gfx/android/orma/test/QueryTest.java

fix #246 include groupBy in Selector#count

---

library/src/test/java/com/github/gfx/android/orma/test/model/ModelIssue248.java
processor/src/main/java/com/github/gfx/android/orma/processor/model/SchemaDefinition.java

Schema generation issues with the same named setters and getters

---

library/src/test/java/com/github/gfx/android/orma/test/ModelSpecTest.java
processor/src/main/java/com/github/gfx/android/orma/processor/generator/ConditionQueryHelpers.java
processor/src/main/java/com/github/gfx/android/orma/processor/generator/UpdaterWriter.java

from https://twitter.com/okugawa3210/status/730992636102746112

let ${Model}Updater#$field() accept null

---

library/src/main/java/com/github/gfx/android/orma/OrmaConnection.java

show query logs in UPDATE statements

---

library/src/test/java/com/github/gfx/android/orma/test/DirectAssociationsTest.java
library/src/test/java/com/github/gfx/android/orma/test/model/ModelWithNullableDirectAssociations.java
processor/src/main/java/com/github/gfx/android/orma/processor/generator/SchemaWriter.java

nullable direct associations

---

build.gradle
example/build.gradle
library/build.gradle
migration/build.gradle
processor/build.gradle

upgrade compileSdkVersion to 24

---

build.gradle
library/build.gradle
library/src/test/resources/robolectric.properties
migration/build.gradle
migration/src/test/resources/robolectric.properties

Update Android gradle plugin to 2.2.0 for v3.0.0

---

example/build/generated/source/apt/debug/com/github/gfx/android/orma/example/orma/OrmaDatabase.java
library/src/main/java/com/github/gfx/android/orma/OrmaConnection.java
library/src/test/java/com/github/gfx/android/orma/test/QueryTest.java
processor/src/main/java/com/github/gfx/android/orma/processor/generator/DatabaseWriter.java

Removed deprecated methods for v3.0

remove deprecated methods

---

example/build/generated/source/apt/debug/com/github/gfx/android/orma/example/orma/Category_Schema.java
example/build/generated/source/apt/debug/com/github/gfx/android/orma/example/orma/Item2_Schema.java
example/build/generated/source/apt/debug/com/github/gfx/android/orma/example/orma/Item_Schema.java
example/build/generated/source/apt/debug/com/github/gfx/android/orma/example/orma/Todo_Schema.java
library/src/test/java/com/github/gfx/android/orma/test/model2/ModelWithDirectAssociation3.java
processor/src/main/java/com/github/gfx/android/orma/processor/generator/SchemaWriter.java

Reported by https://github.com/gfx/Android-Orma/issues/189#issuecomment-252638418

make constructors of Schema public

---

library/src/test/java/com/github/gfx/android/orma/test/model/Issue293.java
library/src/test/java/com/github/gfx/android/orma/test/model/Model293.java
processor/src/main/java/com/github/gfx/android/orma/processor/model/SchemaDefinition.java

Fix #293 by using `@Setter` and `@Getter` as the first priority accessors.

The order of methods should not matter

---

library/src/main/java/com/github/gfx/android/orma/Relation.java
library/src/test/java/com/github/gfx/android/orma/test/RelationTest.java

copy Relation#orderSpecs in clone()

---

example/build/generated/source/apt/debug/com/github/gfx/android/orma/example/orma/Item2_Deleter.java
example/build/generated/source/apt/debug/com/github/gfx/android/orma/example/orma/Item2_Relation.java
example/build/generated/source/apt/debug/com/github/gfx/android/orma/example/orma/Item2_Schema.java
example/build/generated/source/apt/debug/com/github/gfx/android/orma/example/orma/Item2_Selector.java
example/build/generated/source/apt/debug/com/github/gfx/android/orma/example/orma/Item2_Updater.java
example/build/generated/source/apt/debug/com/github/gfx/android/orma/example/orma/OrmaDatabase.java
example/src/main/java/com/github/gfx/android/orma/example/orma/Item2.java
library/src/test/java/com/github/gfx/android/orma/test/DirectAssociationsTest.java
library/src/test/java/com/github/gfx/android/orma/test/model/ModelWithNullableDirectAssociations.java
processor/src/main/java/com/github/gfx/android/orma/processor/generator/SchemaWriter.java

allow @Nullable direct associations in fetching values

---

library/src/test/java/com/github/gfx/android/orma/test/SchemaTest.java
processor/src/main/java/com/github/gfx/android/orma/processor/model/ColumnDefinition.java

storage type of direct associations was wrongly specified as BLOB

---

README.md

Fix deserialized type in README

---

annotations/src/main/java/com/github/gfx/android/orma/annotation/Column.java
library/src/test/java/com/github/gfx/android/orma/test/ForeignKeysTest.java
library/src/test/java/com/github/gfx/android/orma/test/model/ModelWithForeignKeyAction.java
processor/src/main/java/com/github/gfx/android/orma/processor/generator/SqlGenerator.java
processor/src/main/java/com/github/gfx/android/orma/processor/model/ColumnDefinition.java

This can be helpful for handling https://github.com/gfx/Android-Orma/issues/294 problems.
See also https://www.sqlite.org/foreignkeys.html

Configuable SQLite Foreign Key Actions

---

library/src/main/java/com/github/gfx/android/orma/ColumnDef.java
library/src/main/java/com/github/gfx/android/orma/Selector.java
library/src/test/java/com/github/gfx/android/orma/test/QueryTest.java
processor/src/main/java/com/github/gfx/android/orma/processor/generator/SchemaWriter.java
processor/src/main/java/com/github/gfx/android/orma/processor/model/ColumnDefinition.java

｀Selector#pluck(column)` returns the list of the specified column selected. Just like as Rails' [pluck()](http://apidock.com/rails/ActiveRecord/Calculations/pluck).

Implement Selector#pluck()

---

library/src/test/java/com/github/gfx/android/orma/test/QueryTest.java
processor/src/main/java/com/github/gfx/android/orma/processor/generator/DatabaseWriter.java

This is just a proxy to `OrmaConnection#rawQuery()`

add OrmaDatabase#rawQuery()

---

CHANGELOG.md

update CHANGELOG for v3.0.0

---

circle.yml
example/build.gradle
example/src/main/res/layout/nav_header_main.xml
library/build.gradle
library/src/main/java/com/github/gfx/android/orma/internal/Aliases.java
migration/build.gradle

Android Gradle Plugin 2.2 downloads SDK components on demand:
https://developer.android.com/studio/intro/update.html

auto-download sdk components

---

README.md
circle.yml
example/build/generated/source/apt/debug/com/github/gfx/android/orma/example/orma/Category_Deleter.java
example/build/generated/source/apt/debug/com/github/gfx/android/orma/example/orma/Category_Relation.java
example/build/generated/source/apt/debug/com/github/gfx/android/orma/example/orma/Category_Selector.java
example/build/generated/source/apt/debug/com/github/gfx/android/orma/example/orma/Category_Updater.java
example/build/generated/source/apt/debug/com/github/gfx/android/orma/example/orma/Todo_Deleter.java
example/build/generated/source/apt/debug/com/github/gfx/android/orma/example/orma/Todo_Relation.java
example/build/generated/source/apt/debug/com/github/gfx/android/orma/example/orma/Todo_Selector.java
example/build/generated/source/apt/debug/com/github/gfx/android/orma/example/orma/Todo_Updater.java
library/src/main/java/com/github/gfx/android/orma/internal/OrmaConditionBase.java
library/src/test/java/com/github/gfx/android/orma/test/ConditionHelpersTest.java
processor/src/main/java/com/github/gfx/android/orma/processor/generator/ConditionQueryHelpers.java
processor/src/main/java/com/github/gfx/android/orma/processor/util/SqlTypes.java

Add `*Between(a, b)` to build `* BETWEEN a AND b`.

Between Helpers

---

library/src/main/java/com/github/gfx/android/orma/OrmaConnection.java
library/src/test/java/com/github/gfx/android/orma/test/toolbox/OrmaFactory.java

because of circleci memory limitation

stop using on-memory db for testing

---

annotations/src/main/java/com/github/gfx/android/orma/annotation/Column.java
circle.yml
example/build.gradle
example/proguard-rules.pro
library/src/main/java/com/github/gfx/android/orma/ColumnDef.java
library/src/test/java/com/github/gfx/android/orma/test/AggregatorTest.java
library/src/test/java/com/github/gfx/android/orma/test/QueryTest.java
library/src/test/java/com/github/gfx/android/orma/test/model/Book.java
library/src/test/java/com/github/gfx/android/orma/test/model/ModelWithPrimitives.java
processor/src/main/java/com/github/gfx/android/orma/processor/generator/ConditionQueryHelpers.java
processor/src/main/java/com/github/gfx/android/orma/processor/generator/SelectorWriter.java
processor/src/main/java/com/github/gfx/android/orma/processor/model/ColumnDefinition.java
processor/src/main/java/com/github/gfx/android/orma/processor/util/Types.java

https://www.sqlite.org/lang_aggfunc.html

Aggregate Functions

---

library/src/test/java/com/github/gfx/android/orma/test/DirectAssociationsTest.java
library/src/test/java/com/github/gfx/android/orma/test/model/ModelWithMoreNestedDirectAssociations.java
processor/src/main/java/com/github/gfx/android/orma/processor/generator/SchemaWriter.java

Fix an issue that deeply nested models are not handled correctly

---

example/build/generated/source/apt/debug/com/github/gfx/android/orma/example/orma/OrmaDatabase.java
library/src/test/java/com/github/gfx/android/orma/test/OrmaDatabaseTest.java
processor/src/main/java/com/github/gfx/android/orma/processor/generator/DatabaseWriter.java

add OrmaDatabase#deleteAll()

---

circle.yml
library/src/main/java/com/github/gfx/android/orma/Selector.java
library/src/main/java/com/github/gfx/android/orma/internal/OrmaIterator.java
library/src/test/java/com/github/gfx/android/orma/test/QueryTest.java
library/src/test/java/com/github/gfx/android/orma/test/toolbox/IteratorUtils.java

Fix OrmaIterator to respect limit clauses

---

library/proguard-rules.pro

cleanup proguard settings; antlr 4.5.3 is android compatible

---

library/src/main/java/com/github/gfx/android/orma/Deleter.java
library/src/main/java/com/github/gfx/android/orma/Relation.java
library/src/main/java/com/github/gfx/android/orma/Selector.java
library/src/main/java/com/github/gfx/android/orma/Updater.java
library/src/main/java/com/github/gfx/android/orma/internal/OrmaConditionBase.java
library/src/test/java/com/github/gfx/android/orma/test/DirectAssociationsTest.java

This is a cherry-picked #350 for `v3` branch.

fix "ambiguous column name" errors in Relation

---

migration/build.gradle

https://github.com/antlr/antlr4/releases/tag/4.6

upgrade ANTLR4 to 4.6

---

README.md
annotations/src/main/java/com/github/gfx/android/orma/annotation/Column.java
annotations/src/main/java/com/github/gfx/android/orma/annotation/Index.java
example/build/generated/source/apt/debug/com/github/gfx/android/orma/example/orma/Entry_Deleter.java
example/build/generated/source/apt/debug/com/github/gfx/android/orma/example/orma/Entry_Relation.java
example/build/generated/source/apt/debug/com/github/gfx/android/orma/example/orma/Entry_Schema.java
example/build/generated/source/apt/debug/com/github/gfx/android/orma/example/orma/Entry_Selector.java
example/build/generated/source/apt/debug/com/github/gfx/android/orma/example/orma/Entry_Updater.java
example/build/generated/source/apt/debug/com/github/gfx/android/orma/example/orma/OrmaDatabase.java
example/src/main/java/com/github/gfx/android/orma/example/orma/Entry.java
library/src/test/java/com/github/gfx/android/orma/test/CompositeIndexTest.java
library/src/test/java/com/github/gfx/android/orma/test/SchemaTest.java
library/src/test/java/com/github/gfx/android/orma/test/model/ModelWithCompositeIndex.java
library/src/test/java/com/github/gfx/android/orma/test/model/ModelWithConditionHelpers.java
migration/src/main/java/com/github/gfx/android/orma/migration/SchemaDiffMigration.java
migration/src/main/java/com/github/gfx/android/orma/migration/sqliteparser/CreateIndexStatement.java
migration/src/test/java/com/github/gfx/android/orma/migration/test/IndexDiffTest.java
processor/src/main/java/com/github/gfx/android/orma/processor/ProcessingContext.java
processor/src/main/java/com/github/gfx/android/orma/processor/generator/ConditionQueryHelpers.java
processor/src/main/java/com/github/gfx/android/orma/processor/generator/SqlGenerator.java
processor/src/main/java/com/github/gfx/android/orma/processor/model/IndexDefinition.java
processor/src/main/java/com/github/gfx/android/orma/processor/model/SchemaDefinition.java

Implement composite index (or multi-column index)

---

example/build/generated/source/apt/debug/com/github/gfx/android/orma/example/orma/Category_Deleter.java
example/build/generated/source/apt/debug/com/github/gfx/android/orma/example/orma/Category_Relation.java
example/build/generated/source/apt/debug/com/github/gfx/android/orma/example/orma/Category_Selector.java
example/build/generated/source/apt/debug/com/github/gfx/android/orma/example/orma/Category_Updater.java
example/build/generated/source/apt/debug/com/github/gfx/android/orma/example/orma/Entry_Deleter.java
example/build/generated/source/apt/debug/com/github/gfx/android/orma/example/orma/Entry_Relation.java
example/build/generated/source/apt/debug/com/github/gfx/android/orma/example/orma/Entry_Selector.java
example/build/generated/source/apt/debug/com/github/gfx/android/orma/example/orma/Entry_Updater.java
example/build/generated/source/apt/debug/com/github/gfx/android/orma/example/orma/Item2_Deleter.java
example/build/generated/source/apt/debug/com/github/gfx/android/orma/example/orma/Item2_Relation.java
example/build/generated/source/apt/debug/com/github/gfx/android/orma/example/orma/Item2_Selector.java
example/build/generated/source/apt/debug/com/github/gfx/android/orma/example/orma/Item2_Updater.java
example/build/generated/source/apt/debug/com/github/gfx/android/orma/example/orma/Item_Deleter.java
example/build/generated/source/apt/debug/com/github/gfx/android/orma/example/orma/Item_Relation.java
example/build/generated/source/apt/debug/com/github/gfx/android/orma/example/orma/Item_Selector.java
example/build/generated/source/apt/debug/com/github/gfx/android/orma/example/orma/Item_Updater.java
example/build/generated/source/apt/debug/com/github/gfx/android/orma/example/orma/Todo_Deleter.java
example/build/generated/source/apt/debug/com/github/gfx/android/orma/example/orma/Todo_Relation.java
example/build/generated/source/apt/debug/com/github/gfx/android/orma/example/orma/Todo_Selector.java
example/build/generated/source/apt/debug/com/github/gfx/android/orma/example/orma/Todo_Updater.java
library/src/main/java/com/github/gfx/android/orma/Deleter.java
library/src/main/java/com/github/gfx/android/orma/Updater.java
library/src/test/java/com/github/gfx/android/orma/test/DirectAssociationsTest.java
processor/src/main/java/com/github/gfx/android/orma/processor/generator/ConditionBaseMethods.java
processor/src/main/java/com/github/gfx/android/orma/processor/generator/DeleterWriter.java
processor/src/main/java/com/github/gfx/android/orma/processor/generator/RelationWriter.java
processor/src/main/java/com/github/gfx/android/orma/processor/generator/SelectorWriter.java
processor/src/main/java/com/github/gfx/android/orma/processor/generator/SqlGenerator.java
processor/src/main/java/com/github/gfx/android/orma/processor/generator/UpdaterWriter.java
processor/src/main/java/com/github/gfx/android/orma/processor/model/ColumnDefinition.java

Extracting common methods to ConditionBaseMethods in processor.

make all the query helper classes clonable

---

circle.yml

😎 
https://discuss.circleci.com/t/show-test-results-for-prospective-merge-of-a-github-pr/1662/8

checkout "merge" reference

---

library/src/test/java/com/github/gfx/android/orma/test/PrimaryKeyWithTypeAdapterTest.java
library/src/test/java/com/github/gfx/android/orma/test/SchemaTest.java
library/src/test/java/com/github/gfx/android/orma/test/model/ModelWithCustomPrimaryKey.java
processor/src/main/java/com/github/gfx/android/orma/processor/generator/ConditionQueryHelpers.java
processor/src/main/java/com/github/gfx/android/orma/processor/generator/UpdaterWriter.java
processor/src/main/java/com/github/gfx/android/orma/processor/model/ColumnDefinition.java

Resolve #368.
There were lots of issues on custom types as foreign keys.

Embedded type as foreign key

---

library/src/test/java/com/github/gfx/android/orma/test/OrmaAdapterTest.java

Add some missing tests inspired by #372.

add tests for adapters

---

library/src/test/java/com/github/gfx/android/orma/test/OrmaAdapterTest.java

touch the cache

---

example/build/generated/source/apt/debug/com/github/gfx/android/orma/example/orma/Category_Schema.java
example/build/generated/source/apt/debug/com/github/gfx/android/orma/example/orma/Entry_Schema.java
example/build/generated/source/apt/debug/com/github/gfx/android/orma/example/orma/Item2_Relation.java
example/build/generated/source/apt/debug/com/github/gfx/android/orma/example/orma/Item2_Schema.java
example/build/generated/source/apt/debug/com/github/gfx/android/orma/example/orma/Item_Relation.java
example/build/generated/source/apt/debug/com/github/gfx/android/orma/example/orma/Item_Schema.java
example/build/generated/source/apt/debug/com/github/gfx/android/orma/example/orma/Todo_Schema.java
library/src/main/java/com/github/gfx/android/orma/Schema.java
processor/src/main/java/com/github/gfx/android/orma/processor/generator/RelationWriter.java
processor/src/main/java/com/github/gfx/android/orma/processor/generator/SchemaWriter.java

Introduced in #379 but not needed on code generation.

Remove create relation

---

library/src/test/java/com/github/gfx/android/orma/test/UpsertTest.java
processor/src/main/java/com/github/gfx/android/orma/processor/generator/RelationWriter.java

Fix a bug reported in https://github.com/DroidKaigi/conference-app-2017/pull/283

fix NPE in cases direcct associations are nullable

---

library/src/main/java/com/github/gfx/android/orma/Relation.java
library/src/test/java/com/github/gfx/android/orma/test/UpsertTest.java
library/src/test/java/com/github/gfx/android/orma/test/model/Author.java

Useful for https://github.com/DroidKaigi/conference-app-2017/pull/283

upsert for collection (Iterable<T>)

---

build.gradle
example/build.gradle
library/build.gradle
migration/src/main/java/com/github/gfx/android/orma/migration/sqliteparser/SelectStatement.java

`com.neenbedankt.android-apt` no longer works with Android Gradle plugin 2.3.0 so I have had to replace it with `annotationProcessor`

upgrade dependencies

---

library/src/main/java/com/github/gfx/android/orma/SingleAssociation.java
library/src/main/java/com/github/gfx/android/orma/Updater.java

Update#putAll() and SingleAssociation(...) are also called from the generated

---

library/src/main/java/com/github/gfx/android/orma/SingleAssociation.java

https://github.com/gfx/Android-Orma/pull/379 introduces a new internal utility `#findByRowId()`.

simplify SingleAssociation's constructor

---

annotations/src/main/java/com/github/gfx/android/orma/annotation/Database.java

Its a little fix.
Thanks super library 👍

Delete needless space

---

example/build/generated/source/apt/normal/debug/com/github/gfx/android/orma/example/orma/Category_AssociationCondition.java
example/build/generated/source/apt/normal/debug/com/github/gfx/android/orma/example/orma/Entry_AssociationCondition.java
example/build/generated/source/apt/normal/debug/com/github/gfx/android/orma/example/orma/Item2_AssociationCondition.java
example/build/generated/source/apt/normal/debug/com/github/gfx/android/orma/example/orma/Item2_Deleter.java
example/build/generated/source/apt/normal/debug/com/github/gfx/android/orma/example/orma/Item2_Relation.java
example/build/generated/source/apt/normal/debug/com/github/gfx/android/orma/example/orma/Item2_Selector.java
example/build/generated/source/apt/normal/debug/com/github/gfx/android/orma/example/orma/Item2_Updater.java
example/build/generated/source/apt/normal/debug/com/github/gfx/android/orma/example/orma/Item_AssociationCondition.java
example/build/generated/source/apt/normal/debug/com/github/gfx/android/orma/example/orma/Item_Deleter.java
example/build/generated/source/apt/normal/debug/com/github/gfx/android/orma/example/orma/Item_Relation.java
example/build/generated/source/apt/normal/debug/com/github/gfx/android/orma/example/orma/Item_Selector.java
example/build/generated/source/apt/normal/debug/com/github/gfx/android/orma/example/orma/Item_Updater.java
example/build/generated/source/apt/normal/debug/com/github/gfx/android/orma/example/orma/Todo_AssociationCondition.java

https://github.com/maskarade/Android-Orma/pull/424

regen example

---

library/src/main/java/com/github/gfx/android/orma/Inserter.java

fix typo in Inserter

---

.gitignore
annotations/build.gradle
core/build.gradle
encryption/build.gradle
library/build.gradle
metadata.gradle
migration/build.gradle
processor/build.gradle

Stop publishing artifacts to my personal account; publish them to https://bintray.com/orma instead.

publish to bintray orma organization

---

.gitattributes

https://help.github.com/articles/customizing-how-changed-files-appear-on-github/

mark example/build/* as generated

---

.circleci/config.yml

tweaks for ci

---

example/build/generated/source/apt/normal/debug/com/github/gfx/android/orma/example/orma/Category_Schema.java
example/build/generated/source/apt/normal/debug/com/github/gfx/android/orma/example/orma/Entry_Schema.java
example/build/generated/source/apt/normal/debug/com/github/gfx/android/orma/example/orma/Item2_AssociationCondition.java
example/build/generated/source/apt/normal/debug/com/github/gfx/android/orma/example/orma/Item2_Deleter.java
example/build/generated/source/apt/normal/debug/com/github/gfx/android/orma/example/orma/Item2_Relation.java
example/build/generated/source/apt/normal/debug/com/github/gfx/android/orma/example/orma/Item2_Schema.java
example/build/generated/source/apt/normal/debug/com/github/gfx/android/orma/example/orma/Item2_Selector.java
example/build/generated/source/apt/normal/debug/com/github/gfx/android/orma/example/orma/Item2_Updater.java
example/build/generated/source/apt/normal/debug/com/github/gfx/android/orma/example/orma/Item_AssociationCondition.java
example/build/generated/source/apt/normal/debug/com/github/gfx/android/orma/example/orma/Item_Deleter.java
example/build/generated/source/apt/normal/debug/com/github/gfx/android/orma/example/orma/Item_Relation.java
example/build/generated/source/apt/normal/debug/com/github/gfx/android/orma/example/orma/Item_Schema.java
example/build/generated/source/apt/normal/debug/com/github/gfx/android/orma/example/orma/Item_Selector.java
example/build/generated/source/apt/normal/debug/com/github/gfx/android/orma/example/orma/Item_Updater.java
example/build/generated/source/apt/normal/debug/com/github/gfx/android/orma/example/orma/OrmaDatabase.java
example/build/generated/source/apt/normal/debug/com/github/gfx/android/orma/example/orma/Todo_Schema.java
library/src/main/java/com/github/gfx/android/orma/Relation.java
library/src/main/java/com/github/gfx/android/orma/Schema.java
library/src/test/java/com/github/gfx/android/orma/test/RelationTest.java
processor/src/main/java/com/github/gfx/android/orma/processor/generator/SchemaWriter.java

Resolve https://github.com/maskarade/Android-Orma/issues/416.

Convert to content values

---

annotations/build.gradle
core/build.gradle
encryption/build.gradle
library/build.gradle
migration/build.gradle

cf. https://github.com/JakeWharton/butterknife/pull/1384

build as Java8

---

migration/src/main/antlr/SQLite.g4

https://github.com/bkiers/sqlite-parser/tree/9adf75ff5eca36f6e541594d2e062349f9ced654

upgrade SQLite parser

---

processor/src/main/java/com/github/gfx/android/orma/processor/ProcessingContext.java

If user creates multiple databases that have different rxJavaSupport setting and share a model class, Orma cannot generate helper classes for the model.
This PR shows an error in the situation for usability.

Show processing error if different rxJavaSupport databases are found
