maskarade/Android-Orma

- library/src/main/java/com/github/gfx/android/orma/adapter/BigDecimalAdapter.java
- library/src/main/java/com/github/gfx/android/orma/adapter/BigIntegerAdapter.java
- library/src/main/java/com/github/gfx/android/orma/adapter/CurrencyAdapter.java
- library/src/main/java/com/github/gfx/android/orma/adapter/TypeAdapterRegistry.java
- library/src/main/java/com/github/gfx/android/orma/adapter/UUIDAdapter.java
- library/src/test/java/com/github/gfx/android/orma/test/ModelSpecTest.java
- library/src/test/java/com/github/gfx/android/orma/test/model/ModelWithTypeAdapters.java
resolve #62 
Now Orma supports currency-related data types: `Currency`, `BigInteger`, and `BigDecimal`.
> more type adapters

- migration/src/main/java/com/github/gfx/android/orma/migration/SchemaDiffMigration.java
- migration/src/main/java/com/github/gfx/android/orma/migration/SqliteDdlBuilder.java
- migration/src/test/java/com/github/gfx/android/orma/migration/test/SchemaDiffTest.java
- migration/src/test/java/com/github/gfx/android/orma/migration/test/TableDiffTest.java
- sqliteparser/build.gradle
- sqliteparser/src/main/java/com/github/gfx/android/orma/sqliteparser/CreateTableStatement.java
- sqliteparser/src/main/java/com/github/gfx/android/orma/sqliteparser/SQLiteComponent.java
- sqliteparser/src/main/java/com/github/gfx/android/orma/sqliteparser/SQLiteDdlCollector.java
- sqliteparser/src/test/java/com/github/gfx/android/orma/sqliteparser/test/SQLiteComponentTest.java
- sqliteparser/src/test/java/com/github/gfx/android/orma/sqliteparser/test/SQLiteParserUtilsTest.java
* `tableDiff` handles type changes, which was just ignored before
* `tableDIff` ignores cases
> make SchemaDiffMigration more robust

- README.md
- library/src/test/java/com/github/gfx/android/orma/test/model/ModelWithAccessors.java
- processor/src/main/java/com/github/gfx/android/orma/processor/ColumnDefinition.java
- processor/src/main/java/com/github/gfx/android/orma/processor/SchemaDefinition.java
Kotlin classes define getters and setters for their properties, so Java code can't access their raw fields.
This PR makes Orma to use getters and setters even if they are not annotated by `@Getter` and `@Setter` to use Kotlin classes as Orma models.
> Guess getters and setters

- library/src/main/java/com/github/gfx/android/orma/OrmaConfiguration.java
- library/src/main/java/com/github/gfx/android/orma/OrmaConnection.java
- library/src/test/java/com/github/gfx/android/orma/test/ConditionHelpersTest.java
- library/src/test/java/com/github/gfx/android/orma/test/ForeignKeysTest.java
- library/src/test/java/com/github/gfx/android/orma/test/MigrationEngineTest.java
- library/src/test/java/com/github/gfx/android/orma/test/ModelSpecTest.java
- library/src/test/java/com/github/gfx/android/orma/test/OrmaAdapterDelegateTest.java
- library/src/test/java/com/github/gfx/android/orma/test/OrmaBuilder.java
- library/src/test/java/com/github/gfx/android/orma/test/OrmaDatabaseTest.java
- library/src/test/java/com/github/gfx/android/orma/test/QueryTest.java
- library/src/test/java/com/github/gfx/android/orma/test/RelationTest.java
- library/src/test/java/com/github/gfx/android/orma/test/ReservedWordsTest.java
- library/src/test/java/com/github/gfx/android/orma/test/RxObservableTest.java
- library/src/test/java/com/github/gfx/android/orma/test/SetterAndGetterTest.java
- migration/src/main/java/com/github/gfx/android/orma/migration/sqliteparser/SQLiteParserUtils.java
This is because the current tests includes "too complex SQL"s (related to #99).
> add OrmaConfiguration#tryParsingSql() to omit parsing SQL in setup

- .gitignore
- example/build.gradle
- example/proguard-rules.pro
- library/build.gradle
- library/proguard-rules.pro
- library/src/main/java/com/github/gfx/android/orma/internal/TypeHolder.java
Orma requires `-keepattributes Signature` for ProGuard.
This PR uses `consumerProguardFiles` to bundle a proguard configuration file in AAR.
> fix crash with proguard; because of missing proguard configuration

- library/src/main/java/com/github/gfx/android/orma/Selector.java
- library/src/test/java/com/github/gfx/android/orma/test/QueryTest.java
close #120.
Introduce `#empty()` instead of `#exists()`. `#exists()` is not natural because there always exists a table (or a relation).
> add Selector#empty()

- library/src/main/java/com/github/gfx/android/orma/OrmaConnection.java
That's because type adapter registry will become global, static object.
related to #49
> deprecate OrmaConnection#getTypeAdapterRegistry()

- library/src/test/java/com/github/gfx/android/orma/test/MigrationEngineTest.java
- migration/src/main/java/com/github/gfx/android/orma/migration/ManualStepMigration.java
- migration/src/main/java/com/github/gfx/android/orma/migration/OrmaMigration.java
- migration/src/main/java/com/github/gfx/android/orma/migration/SchemaDiffMigration.java
- migration/src/test/java/com/github/gfx/android/orma/migration/test/OrmaMigrationTest.java
`ApplicationInfo#lastUpdateTime` is not reliable because users can change device time easily. That is, the `lastUpdateTime` based migration trigger might not be reliable, neither.
A newly introduced class, `OrmaMigration.Builder` supports `autoSchemaVersion` mode where `VERSION_CODE` is used on release build, while `lastUpdateTime` is used on debug build.
See `OrmaMigrationTest#testBuilder()` for details.
> Add OrmaMiration.builder(Context); deprecate old OrmaMigration consractors

- migration/src/main/java/com/github/gfx/android/orma/migration/AbstractMigrationEngine.java
- migration/src/main/java/com/github/gfx/android/orma/migration/ManualStepMigration.java
- migration/src/main/java/com/github/gfx/android/orma/migration/OrmaMigration.java
- migration/src/main/java/com/github/gfx/android/orma/migration/SchemaDiffMigration.java
It's safer to use `BuildConfig.VERSION_CODE` in SchemaDiffMigration than `ApplicationInfo#lastUpdateTime`.
> make SchemaDiffMigration to use versioning which is the same logic as OrmaMigration

- example/build.gradle
- migration/build.gradle
Because Android DataBinding 1.1 uses https://github.com/tunnelvisionlabs/antlr4, which is a fork of the official antlr4 with the same package name, this project have to use tunnelvisionlabs/antlr4 too.
Maybe related to #133
> Use tunnelvisionlabs/antlr4

- annotations/src/main/java/com/github/gfx/android/orma/annotation/Column.java
- annotations/src/main/java/com/github/gfx/android/orma/annotation/Getter.java
- annotations/src/main/java/com/github/gfx/android/orma/annotation/OnConflict.java
- annotations/src/main/java/com/github/gfx/android/orma/annotation/PrimaryKey.java
- annotations/src/main/java/com/github/gfx/android/orma/annotation/Setter.java
- annotations/src/main/java/com/github/gfx/android/orma/annotation/StaticTypeAdapter.java
- annotations/src/main/java/com/github/gfx/android/orma/annotation/Table.java
- annotations/src/main/java/com/github/gfx/android/orma/annotation/VirtualTable.java
Kapt uses class files as binary stubs, which do not include `RetentionPolicy.SOUCE` annotations.
This is described in http://blog.jetbrains.com/kotlin/2015/06/better-annotation-processing-supporting-stubs-in-kapt/ and should be removed in a future version.
Thanks to @sys1yagi to blog this issue: http://sys1yagi.hatenablog.com/entry/2016/02/02/130402 (ja)
> use RetentionPolicy.CLASS for kapt bugs

- library/build.gradle
- library/src/main/java/com/github/gfx/android/orma/SingleAssociation.java
- library/src/main/java/com/github/gfx/android/orma/gson/SingleAssociationTypeAdapterFactory.java
- library/src/test/java/com/github/gfx/android/orma/test/GsonTypeAdapterTest.java
NOTE: Orma does not have a dependency to Gson. It is still optional.
> implements SingleAssociationTypeAdapterFactory for Gson

- library/src/main/java/com/github/gfx/android/orma/Inserter.java
- library/src/main/java/com/github/gfx/android/orma/OrmaConnection.java
- library/src/main/java/com/github/gfx/android/orma/Relation.java
- library/src/main/java/com/github/gfx/android/orma/Schema.java
- library/src/test/java/com/github/gfx/android/orma/test/QueryTest.java
- library/src/test/java/com/github/gfx/android/orma/test/SchemaTest.java
- processor/src/main/java/com/github/gfx/android/orma/processor/DatabaseWriter.java
- processor/src/main/java/com/github/gfx/android/orma/processor/SchemaDefinition.java
- processor/src/main/java/com/github/gfx/android/orma/processor/SchemaWriter.java
- processor/src/main/java/com/github/gfx/android/orma/processor/SqlGenerator.java
`withoutAutoId` is added to `Inserter#<init>` as a low-level interface to UPSERT.
`Inserter<T> Relation#upserter()` is added as a high-level interface to UPSERT.
> withoutAutoId option for UPSERT operations

- README.md
- library/src/main/java/com/github/gfx/android/orma/OrmaConfiguration.java
`OrmaDatabase.builder(context).trace(true)` enables migration tracing, too.
> make enabling migration tracing easier

- library/src/main/java/com/github/gfx/android/orma/Selector.java
- library/src/main/java/com/github/gfx/android/orma/SingleAssociation.java
- library/src/test/java/com/github/gfx/android/orma/test/ForeignKeysTest.java
- library/src/test/java/com/github/gfx/android/orma/test/QueryTest.java
#168 
* Remove `Selector#empty()`; use `#isEmpty()` instead
* Remove `SingleAssociation#single()`; use `#observable()` instead
* Change `Observable<Integer> countAsObservable()` to `Single<Integer> countAsObservable()` for consistency
> remove deprecated methods and fix inconsistent methods

- library/src/test/java/com/github/gfx/android/orma/test/SchemaTest.java
- library/src/test/java/com/github/gfx/android/orma/test/model/BaseModel.java
- library/src/test/java/com/github/gfx/android/orma/test/model/ModelWithInheritance.java
- processor/src/main/java/com/github/gfx/android/orma/processor/SchemaValidator.java
- processor/src/main/java/com/github/gfx/android/orma/processor/model/SchemaDefinition.java
- processor/src/test/java/com/github/gfx/android/orma/processor/test/SchemaValidatorTest.java
- processor/src/test/resources/ModelInheritance.java
Base classes must not be Orma models. STI (single table inheritance) is not supported.
> support model inheritance

- processor/src/main/java/com/github/gfx/android/orma/processor/model/SchemaDefinition.java
I fixed the bad comparator of columns in SchemaDefinition.
Sorting of columns has the purpose which is `Places primaryKey as the last in columns to handle withoutAutoId.`
However, given comparator is not correct.
If the `@PrimaryKey` column is not the first field, it will be moved to the first element of `columns`.
In addition, when PrimaryKey.auto is declared as `true`, `convertToArgs()` always throws `ArrayIndexOutOfBoundsException`.
Sort check program is following.
http://ideone.com/wn4fBv
The new comparator has the pre-condition -- `One table can have one PrimaryKey at most. `
> Fixed ArrayIndexOutOfBoundsException with convertToArgs()

- library/src/test/java/com/github/gfx/android/orma/test/model/ModelWithInheritanceWIthoutColumns.java
- processor/src/main/java/com/github/gfx/android/orma/processor/OrmaProcessor.java
- processor/src/main/java/com/github/gfx/android/orma/processor/SchemaValidator.java
- processor/src/main/java/com/github/gfx/android/orma/processor/model/SchemaDefinition.java
Let SchemaValidator work for `SchemaDefinition`, instead of `TypeElement`, to handle inherited models easily.
> fix #220 schmea validators raise errors in model inheritance

- library/src/main/java/com/github/gfx/android/orma/OrmaConnection.java
- library/src/main/java/com/github/gfx/android/orma/Selector.java
OrmaConnection should have only low-level methods, but `count()` is kind of high-level methods.
> remove OrmaConnection#count() method

- processor/src/main/java/com/github/gfx/android/orma/processor/OrmaProcessor.java
- processor/src/main/java/com/github/gfx/android/orma/processor/ProcessingContext.java
As of JavaPoet 1.6.0, `JavaFile#writeTo(Filer)` is not thread-safe, so add a thread-safe version.
> Pararell annotation processing

- example/build/generated/source/apt/debug/com/github/gfx/android/orma/example/orma/OrmaDatabase.java
- example/src/main/java/com/github/gfx/android/orma/example/activity/BenchmarkActivity.java
- example/src/main/java/com/github/gfx/android/orma/example/activity/ListViewActivity.java
- example/src/main/java/com/github/gfx/android/orma/example/activity/RecyclerViewActivity.java
- library/src/main/java/com/github/gfx/android/orma/OrmaConnection.java
- library/src/main/java/com/github/gfx/android/orma/Relation.java
- library/src/main/java/com/github/gfx/android/orma/widget/OrmaAdapter.java
- library/src/main/java/com/github/gfx/android/orma/widget/OrmaListAdapter.java
- library/src/main/java/com/github/gfx/android/orma/widget/OrmaRecyclerViewAdapter.java
- library/src/test/java/com/github/gfx/android/orma/test/QueryTest.java
- processor/src/main/java/com/github/gfx/android/orma/processor/generator/DatabaseWriter.java
- processor/src/main/java/com/github/gfx/android/orma/processor/util/Annotations.java
- processor/src/main/java/com/github/gfx/android/orma/processor/util/Types.java
improve OrmaAdapter to evaluate use cases.
* make `getRelation()` return a clone
* fix the return type of `getRelation()`
* add `Relation#value()` as a shortcut of `relation.selector().value()`
* add `void transactionSync(Runnable)`
* add `Completable transactionAsync(Runnable)`
> Improve OrmaAdapter

- library/src/test/java/com/github/gfx/android/orma/test/model/ModelWithAccessors.java
- processor/src/main/java/com/github/gfx/android/orma/processor/model/SchemaDefinition.java
This amends https://github.com/gfx/Android-Orma/pull/224
Now Orma uses both `@Column(name)` and its fiend name in order to find the corresponding getters and setters.
cc: @nein37
> use @Column#name first to find getters and setters

- library/src/test/java/com/github/gfx/android/orma/test/model/ModelWithGenericSuperClass.java
- library/src/test/java/com/github/gfx/android/orma/test/model/ModelWithGenerics.java
- processor/src/main/java/com/github/gfx/android/orma/processor/ProcessingContext.java
- processor/src/main/java/com/github/gfx/android/orma/processor/model/SchemaDefinition.java
Note that you can't use type parameters for `@Column` because table definitions in SQLite can't be generic.
connect #265
> Fix#265 generic superl classes caused compilation errors

- library/src/main/java/com/github/gfx/android/orma/ModelFactory.java
To make RxJava optional in a future.
> use Callable<T> instead of rx.functions.Func0

- library/build.gradle
Note that 1.1.7 includes breaking changes on `Completable`, which is marked as `@Experimental`.
See https://github.com/ReactiveX/RxJava/releases/tag/v1.1.7 for details.
> upgrade RxJava to 1.1.7

- example/build/generated/source/apt/debug/com/github/gfx/android/orma/example/orma/OrmaDatabase.java
- gradle/wrapper/gradle-wrapper.properties
- library/src/main/java/com/github/gfx/android/orma/BuiltInSerializers.java
- library/src/test/java/com/github/gfx/android/orma/test/RxObservableTest.java
- processor/src/main/java/com/github/gfx/android/orma/processor/generator/DatabaseWriter.java
- processor/src/main/java/com/github/gfx/android/orma/processor/util/Types.java
> Parepare insert as observable

- example/build/generated/source/apt/debug/com/github/gfx/android/orma/example/orma/Category_Schema.java
- example/build/generated/source/apt/debug/com/github/gfx/android/orma/example/orma/Item2_Schema.java
- example/build/generated/source/apt/debug/com/github/gfx/android/orma/example/orma/Item_Schema.java
- example/build/generated/source/apt/debug/com/github/gfx/android/orma/example/orma/Todo_Schema.java
- library/src/test/java/com/github/gfx/android/orma/test/SchemaTest.java
- processor/src/main/java/com/github/gfx/android/orma/processor/generator/SchemaWriter.java
Don't use names with `/^[a-zA-Z0-9_]+$/` in `Schema` because they are reserved for column names.
> use `$alias` in Schema, to avoid name conflicts with columns

- example/build/generated/source/apt/debug/com/github/gfx/android/orma/example/orma/Category_Selector.java
- example/build/generated/source/apt/debug/com/github/gfx/android/orma/example/orma/Item2_Selector.java
- example/build/generated/source/apt/debug/com/github/gfx/android/orma/example/orma/Item_Selector.java
- example/build/generated/source/apt/debug/com/github/gfx/android/orma/example/orma/Todo_Selector.java
- library/src/main/java/com/github/gfx/android/orma/Selector.java
- library/src/test/java/com/github/gfx/android/orma/test/QueryTest.java
- processor/src/main/java/com/github/gfx/android/orma/processor/generator/SelectorWriter.java
Fix a problem that `Selector#orderBy` is ignored in `Selector#clone` and `new Selector(selector)`.
cc: @sys1yagi
> respect orderBy terms in Selector#clone()

- library/src/main/java/com/github/gfx/android/orma/BuiltInSerializers.java
- library/src/test/java/com/github/gfx/android/orma/test/ModelSpecTest.java
- library/src/test/java/com/github/gfx/android/orma/test/model/ModelWithTypeAdapters.java
- library/src/test/java/com/github/gfx/android/orma/test/toolbox/EnumA.java
- library/src/test/java/com/github/gfx/android/orma/test/toolbox/EnumB.java
- library/src/test/java/com/github/gfx/android/orma/test/toolbox/EnumDescription.java
- library/src/test/java/com/github/gfx/android/orma/test/type_adapter/EnumTypeAdapter.java
- processor/src/main/java/com/github/gfx/android/orma/processor/ProcessingContext.java
- processor/src/main/java/com/github/gfx/android/orma/processor/generator/SchemaWriter.java
- processor/src/main/java/com/github/gfx/android/orma/processor/model/ColumnDefinition.java
- processor/src/main/java/com/github/gfx/android/orma/processor/model/TypeAdapterDefinition.java
- processor/src/main/java/com/github/gfx/android/orma/processor/util/SqlTypes.java
- processor/src/main/java/com/github/gfx/android/orma/processor/util/Types.java
Given an interface `EnumDescription` and enum `EnumA` and `EnumB` which implement `EnumDescription`, type adapter for `EnumDescription` can handle its descendants, `EnumA` and `EnumB`:
```java
@StaticTypeAdapter(
targetType = EnumDescription.class,
serializedType = String.class
)
public class EnumTypeAdapter {
public static <T extends Enum<T> & EnumDescription> String serialize(@NonNull T value) {
return value.name();
}
@SuppressWarnings("unchecked")
@NonNull
public static <T extends Enum<T> & EnumDescription> T deserialize(@NonNull String serialized, @NonNull Class<T> type) {
return Enum.valueOf(type, serialized);
}
}
```
> Support generic type adapters

- migration/src/main/java/com/github/gfx/android/orma/migration/SqliteDdlBuilder.java
- migration/src/test/java/com/github/gfx/android/orma/migration/test/TableDiffTest.java
Resolve  #326.
ref. https://www.sqlite.org/lang_keywords.html 
> **[keyword]**		A keyword enclosed in square brackets is an identifier. This is not standard SQL. This quoting mechanism is used by MS Access and SQL Server and is included in SQLite for compatibility.
> Allows square brackets to escape identifiers

- README.md
- annotations/src/main/java/com/github/gfx/android/orma/annotation/Experimental.java
- build.gradle
- example/build.gradle
- library/build.gradle
- library/src/main/java/com/github/gfx/android/orma/Inserter.java
- library/src/main/java/com/github/gfx/android/orma/OrmaConnection.java
- library/src/main/java/com/github/gfx/android/orma/Relation.java
- library/src/main/java/com/github/gfx/android/orma/event/DataSetChangedEvent.java
- library/src/main/java/com/github/gfx/android/orma/event/DataSetChangedTrigger.java
- library/src/main/java/com/github/gfx/android/orma/widget/OrmaAdapter.java
- library/src/main/java/com/github/gfx/android/orma/widget/OrmaListAdapter.java
- library/src/main/java/com/github/gfx/android/orma/widget/OrmaRecyclerViewAdapter.java
- library/src/test/java/com/github/gfx/android/orma/test/QueryObservableTest.java
* https://github.com/square/sqlbrite
* https://realm.io/docs/swift/latest/#notifications
example:
```java
final List<String> result = new ArrayList<>();
Observable<DataSetChangedEvent<Author_Selector>> observable = db.relationOfAuthor().createQueryObservable();
observable.flatMap(new Function<DataSetChangedEvent<Author_Selector>, Observable<Author>>() {
@Override
public Observable<Author> apply(DataSetChangedEvent<Author_Selector> event) throws Exception {
return event.getSelector().executeAsObservable();
}
}).map(new Function<Author, String>() {
@Override
public String apply(Author author) throws Exception {
return author.name;
}
}).subscribe(new Consumer<String>() {
@Override
public void accept(String s) throws Exception {
result.add(s);
}
});
// fire an event …
```
> SQLBrite-like query observables

- library/src/main/java/com/github/gfx/android/orma/widget/OrmaAdapter.java
- library/src/main/java/com/github/gfx/android/orma/widget/OrmaListAdapter.java
- library/src/main/java/com/github/gfx/android/orma/widget/OrmaRecyclerViewAdapter.java
OrmaListAdapter and OrmaRecyclerViewAdapter are experimental, so they are now  marked as `@Experimental`.
> mark orma.wiget.* experimental

- circle.yml
https://developer.android.com/studio/command-line/sdkmanager.html
Need to upgrade "tools" with android(1) because Android SDK installed in Circle CI is too old.
> use the new sdkmanager(1)

- example/src/main/java/com/github/gfx/android/orma/example/fragment/BenchmarkFragment.java
I updated realm's insert benchmark to use faster insert api.
https://realm.io/news/realm-java-1.1.0/
Result on Nexus6 7.0
before | after
--- | ---
Apparently Orma is much faster though :)
> use realm's insert api for better performance

- annotations/src/main/java/com/github/gfx/android/orma/annotation/OnConflict.java
- example/build/generated/source/apt/debug/com/github/gfx/android/orma/example/orma/Category_Relation.java
- example/build/generated/source/apt/debug/com/github/gfx/android/orma/example/orma/Category_Schema.java
- example/build/generated/source/apt/debug/com/github/gfx/android/orma/example/orma/Entry_Relation.java
- example/build/generated/source/apt/debug/com/github/gfx/android/orma/example/orma/Entry_Schema.java
- example/build/generated/source/apt/debug/com/github/gfx/android/orma/example/orma/Item2_Relation.java
- example/build/generated/source/apt/debug/com/github/gfx/android/orma/example/orma/Item2_Schema.java
- example/build/generated/source/apt/debug/com/github/gfx/android/orma/example/orma/Item_Relation.java
- example/build/generated/source/apt/debug/com/github/gfx/android/orma/example/orma/Item_Schema.java
- example/build/generated/source/apt/debug/com/github/gfx/android/orma/example/orma/Todo_Relation.java
- example/build/generated/source/apt/debug/com/github/gfx/android/orma/example/orma/Todo_Schema.java
- library/src/main/java/com/github/gfx/android/orma/OrmaConnection.java
- library/src/main/java/com/github/gfx/android/orma/Relation.java
- library/src/main/java/com/github/gfx/android/orma/Schema.java
- library/src/main/java/com/github/gfx/android/orma/SingleAssociation.java
- library/src/main/java/com/github/gfx/android/orma/Updater.java
- library/src/test/java/com/github/gfx/android/orma/test/QueryTest.java
- library/src/test/java/com/github/gfx/android/orma/test/RelationTest.java
- library/src/test/java/com/github/gfx/android/orma/test/UpsertTest.java
- library/src/test/java/com/github/gfx/android/orma/test/model/Book.java
- library/src/test/java/com/github/gfx/android/orma/test/model/ModelWithDirectAssociation.java
- processor/src/main/java/com/github/gfx/android/orma/processor/generator/ConditionQueryHelpers.java
- processor/src/main/java/com/github/gfx/android/orma/processor/generator/RelationWriter.java
- processor/src/main/java/com/github/gfx/android/orma/processor/generator/SchemaWriter.java
- processor/src/main/java/com/github/gfx/android/orma/processor/generator/UpdaterWriter.java
- processor/src/main/java/com/github/gfx/android/orma/processor/model/ColumnDefinition.java
Resolve #294 by adding a new `Relation#upsert()` method.
Because this is a high-level method, it is defined in `Relation`, not in `OrmaDatabase`.
Also deprecates `Relation#upserter()` because it is very confusing. Use `#inserter(OnConflict.REPLACE)` if you know what to do.
---
the initial, generic version of `#upsertWithoutTransaction()`:
```java
@SuppressWarnings("unchecked")
@NonNull
public <PK> Model upsertWithoutTransaction(@NonNull final Model model) {
Schema<Model> schema = getSchema();
ContentValues contentValues = new ContentValues();
for (ColumnDef<Model, ?> column : schema.getColumns()) {
if (column.isPrimaryKey() && column.isAutoValue()) {
// nothing to do
} else if (column instanceof AssociationDef) {
Object newAssociatedModel = updateOrInsertForAssociation(((AssociationDef) …
```
> implement Relation#upsert()

- library/src/main/java/com/github/gfx/android/orma/Selector.java
- library/src/main/java/com/github/gfx/android/orma/internal/package-info.java
- migration/src/main/java/com/github/gfx/android/orma/migration/sqliteparser/package-info.java
Restricting `com.github.gfx.android.orma.internal` is too strict that it causes lint errors because they are used in the generated classes.
`LIBRARY_GROUP` allows example to use them so I cannot find this issue in the project.
> @RestrictTo should not be used for classes that are used for the generated

- library/src/main/java/com/github/gfx/android/orma/Selector.java
- library/src/test/java/com/github/gfx/android/orma/test/QueryTest.java
Currently, `Selector#value()` and `Selector#valueOrNull()` returns the first model whether or not to specify `Selector#offset()`.
```java
orma.selectFromTodo()
.offset(10)
.value(); // returns the 1st todo without any warning!
```
Of course we can do the aimed thing as
```java
orma.selectFromTodo().get(10);
```
but current behavior makes me a little confusable.
So I changed these methods to respects `offset`.
How do you think?
> change Selector#value() to respect Selector#offset()

- library/src/main/java/com/github/gfx/android/orma/internal/OrmaConditionBase.java
- library/src/test/java/com/github/gfx/android/orma/test/QueryTest.java
I added `Selector#conditionGroup()` to build complex condition like:
```java
db.selectFromBook()
.conditionGroup(it -> it.titleEq("Hoge").or().titleEq("Huga"))
.and()
.publisherEq(publisher)
.toList();
```
The result SQL is `SELECT * FROM Book WHERE (title = "Hoge" OR title = "Huga") AND publisherId = 1`.
> add Selector#where(C)

- library/src/main/java/com/github/gfx/android/orma/Relation.java
- library/src/main/java/com/github/gfx/android/orma/Selector.java
- library/src/main/java/com/github/gfx/android/orma/Updater.java
- library/src/main/java/com/github/gfx/android/orma/internal/OrmaConditionBase.java
- library/src/test/java/com/github/gfx/android/orma/test/QueryTest.java
- library/src/test/java/com/github/gfx/android/orma/test/model/Book.java
`where(Function<C, C>)` is just an alias to `where(block.apply((C) clone()))`
`clone()` makes it a real function without side-effect.
cc: @k-kagurazaka
> Cleanup condition group

- library/src/main/java/com/github/gfx/android/orma/OrmaConnection.java
Title says everything.
Some situations require  close and re-build database, `close()` method allow us to do it.
> add close() into OrmaConnection

- library/src/main/java/com/github/gfx/android/orma/Inserter.java
- processor/src/main/java/com/github/gfx/android/orma/processor/generator/DatabaseWriter.java
#409 
It seems that SQLCipher is a bit more strict than platform's SQLiteDatabase.
> ensure to close statements in OrmaDatabase#insertInto*()

- library/src/main/java/com/github/gfx/android/orma/internal/OrmaConditionBase.java
The result of `clone()` completely has the current clause, so there is no need to pass it to `where` again.
> fix a bug that where(block) includes duplicated clause

- library/src/main/java/com/github/gfx/android/orma/event/DataSetChangedTrigger.java
To fix https://github.com/gfx/Android-Orma/issues/420
> Use concurrent weak map

- library/src/main/java/com/github/gfx/android/orma/internal/OrmaConditionBase.java
- library/src/test/java/com/github/gfx/android/orma/test/QueryTest.java
It's a fix for a bug embedded in #415 .
I use "copy & reset" to obtain the clean condition instance.
Of course I know it's not beautiful but looks little better than [former my code](https://github.com/k-kagurazaka/Android-Orma/blob/a28149e829d5e330685bc7840abc48daf4ae8a66/library/src/main/java/com/github/gfx/android/orma/internal/OrmaConditionBase.java#L185).
I welcome more smart solution.
> fix a bug that where(block) doesn't wrap conditions by parenthesis

- README.md
For auto-migration case, newlly added column must have defultExpr
or @Nullable explicitly, but this was only explained Japanese blog entry.
http://gfx.hatenablog.com/entry/2016/01/12/093529
This PR just add these note.
> Update readome for migration.

- library/src/test/java/com/github/gfx/android/orma/test/SetterAndGetterTest.java
- library/src/test/java/com/github/gfx/android/orma/test/model/ModelWithMultipleSetterConstructors.java
- processor/src/main/java/com/github/gfx/android/orma/processor/model/SchemaDefinition.java
- processor/src/test/java/com/github/gfx/android/orma/processor/test/SchemaValidatorTest.java
- processor/src/test/resources/AmbiguousSetterConstructors.java
Related #438 
Currently, Orma requires that `@Setter` annotated constructor should be unique.
However this limitation is not convenient when model classes are written by Kotlin with the primary constructor and default arguments since Kotlin compiler gives `@Setter` annotation to all constructors if the primary constructor has `@JvmOverloads` annotation.
This PR relaxes the limitation. If multiple `@Setter` constructors are found, Orma uses a constructor with arguments of which count is the same as a number of columns.
The modification makes it possible for us to write following code:
```kotlin
@Table
class OrmaTodo @JvmOverloads @Setter constructor(
@PrimaryKey var id: Long,
@Column var foo: String,
var bar: Int? = null
)
```
How about this suggestion?
> Relax limitation of @Setter constructors to support Kotlin model class with default argument

- build.gradle
- library/build.gradle
- migration/build.gradle
Now robolectric 4.0 has the same functionality as [Robolectric-Instrumentation](https://github.com/maskarade/Robolectric-Instrumentation).
> migration to Robolectric 4.0; goodbye Robolectric-Instrumentation!
